---
apiVersion: batch/v1
kind: Job
metadata:
  name: counter
  namespace: argo
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - args:
        - q=0; while [[ q -lt 300 ]]; do sleep 1 && ((q++)); echo $q; done
        command:
        - /bin/bash
        - -c
        - --
        env:
        - name: DEBUG
          value: "true"
        image: ubuntu:latest
        name: counter
      restartPolicy: Never
